src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehicleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\SluggerInterface;

#[ORM\Entity(repositoryClass: VehicleRepository::class)]
#[ORM\Index(columns: ['brand', 'model'], name: 'vehicle_idx', flags: ['fulltext'])]
class Vehicle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column]
    private ?int $milliage = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\ManyToOne(inversedBy: 'vehicle')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'vehicle')]
    private ?VehicleType $vehicleType = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'vehicle', targetEntity: Gallery::class, orphanRemoval: true)]
    private Collection $galleries;

    public function __construct()
    {
        $this->galleries = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->brand;
    }

    public function computeSlug(SluggerInterface $slugger): void
    {
        $this->slug = (string) $slugger->slug($this->brand .'-'. $this->model)->lower();
    }

    public function getFullBrand()
    {
        return $this->brand .' '. $this->model;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getMilliage(): ?int
    {
        return $this->milliage;
    }

    public function setMilliage(int $milliage): static
    {
        $this->milliage = $milliage;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getVehicleType(): ?VehicleType
    {
        return $this->vehicleType;
    }

    public function setVehicleType(?VehicleType $vehicleType): static
    {
        $this->vehicleType = $vehicleType;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Gallery>
     */
    public function getGalleries(): Collection
    {
        return $this->galleries;
    }

    public function addGallery(Gallery $gallery): static
    {
        if (!$this->galleries->contains($gallery)) {
            $this->galleries->add($gallery);
            $gallery->setVehicle($this);
        }

        return $this;
    }

    public function removeGallery(Gallery $gallery): static
    {
        if ($this->galleries->removeElement($gallery)) {
            // set the owning side to null (unless already changed)
            if ($gallery->getVehicle() === $this) {
                $gallery->setVehicle(null);
            }
        }

        return $this;
    }
}

src/Controller/SingleCarController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Vehicle;
use App\Form\OrderFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SingleCarController extends AbstractController
{
    #[Route('/vehicle/{slug}', name: 'vehicle_details')]
    public function index(Vehicle $vehicle, Request $request, EntityManagerInterface $manager): Response
    {
        $message = new Message();
        $form = $this->createForm(OrderFormType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setCreatedAt(new \DateTimeImmutable());
            $manager->persist($message);
            $manager->flush();
            $this->addFlash('success', 'Message envoyé avec succès.');
            return $this->redirectToRoute('vehicle_details', ['slug' => $vehicle->getSlug(), '_fragment' => 'orderForm']);
        }

        return $this->render('single_car/index.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form->createView()
        ]);
    }
}

templates/single_car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ vehicle.brand }} {{ vehicle.model }}{% endblock %}

{% block body %}

    <body class="bg-soft-white">
        <section class="detail-banner"
                 style="background: linear-gradient(to bottom, rgba(0, 0, 0, 0.35), rgba(0, 0, 0, 0.75)),
                         url({{ asset('upload/images/vehicles-illustration/' ~ vehicle.image) }}) ;">
            <div class="container h-100">
                <div class="breadcrumb-container h-100">
                    <div class="breadcrumb-area d-flex justify-content-center align-items-center flex-column h-100">
                        <h1 class="text-light fw-700 barlow">{{ vehicle.fullBrand }}</h1>
                        <ul class="breadcrumb d-flex gap-2 text-light fw-600">
                            <li><a href="{{ path('app_home') }}">Accueil</a></li>
                            <li>/ Véhicules</li>
                            <li>/ {{ vehicle.fullBrand }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <section class="car-details py-120">
            <div class="container">
                <div class="d-flex mb-md-3 w-100 justify-content-between align-items-center">
                    <h3 class="car-name barlow fw-600 letter-spacing-02 text-capitalize">{{ vehicle.fullBrand }}</h3>
                    <h3 class="car-price barlow letter-spacing-02 fw-600 text-red">${{ vehicle.price }}</h3>
                </div>
                <div class="row">
                    <div class="car-details-section bg-white p-3">
                        <div class="car-pictures">
                            <div class="row">
                                <div class="col-md-3 col-sm-12 mb-3">
                                    <div class="d-flex justify-content-between align-items-center gap-3 flex-md-column flex-sm-row">
                                        {% for image in vehicle.galleries %}
                                            <div class="car-thumbnail">
                                                <img src="{{ asset('upload/images/vehicles-illustration/' ~ image.image) }}" class="img-fluid
                                                rounded-1"
                                                     alt="">
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="col-md-9 col-sm-12">
                                    <div class="car-picture-main">
                                        <img src="{{ asset('upload/images/vehicles-illustration/' ~ vehicle.image) }}" class="w-100 rounded-1" alt="">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="car-desc mt-3">
                    <h3 class="barlow letter-spacing-02 text-red">Description</h3>
                    {{ vehicle.description | raw }}
                </div>

                <div class="row" id="orderForm">
                    <div class="col-md-8 col-sm-10">
                        <div class="contact-form py-3">
                            <h4 class="text-capitalize mb-3 fw-600 barlow letter-spacing-02">
                                Commander la <span class="text-red">{{ vehicle.fullBrand }}</span>
                            </h4>

                            {% for message in app.flashes('success') %}
                                <div class="alert alert-success d-flex align-items-center" role="alert">
                                    <span class="material-icons-outlined">task_alt </span>
                                    <div>
                                        {{ message }}
                                    </div>
                                </div>
                            {% endfor %}

                            {{ form_start(form) }}
                            <div class="row">
                                <div class="col-md-6 col-sm-12 mb-3">
                                    {{ form_row(form.name) }}
                                </div>
                                <div class="col-md-6 col-sm-12 mb-3">
                                    {{ form_row(form.email) }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-12 mb-3">
                                    {{ form_row(form.subject) }}
                                </div>
                                <div class="col-md-6 col-sm-12 mb-3">
                                    {{ form_row(form.phone) }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 mb-3">
                                    {{ form_row(form.message) }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <button type="submit" class="btn bg-red rounded-0  d-flex gap-1 align-items-center">
                                        Envoyer le message
                                        <span class="material-icons-outlined">send</span>
                                    </button>
                                </div>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </body>
{% endblock %}